#!/bin/sh
ssh ubuntu@ec2-52-2-168-14.compute-1.amazonaws.com <<EOF
    cd ~/avengers-frontend
    git pull origin aws
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
    . ~/.nvm/nvm.sh
    nvm install node
    npm install
    npm install -g @angular/cli
    ng build --prod
    ng serve --prod
    exit
EOF
